### ISSUE TITLE
Consider making *ring* dependency optional

### ISSUE THREAD

**Issue by ctz** [rustls/webpki#130]
The ultimate goal here would be to allow use of the webpki crate with other cryptography libraries.

This would come in two parts, I think:

- replacing remaining references to `ring::io` -- much of this was already done, but a handful of instances remain.
- rework `SignatureAlgorithm` to be a trait that can be implemented outside the crate, with implementations backed by *ring* being provided by default (eg, `ECDSA_P256_SHA256`). Alongside, we should export `AlgorithmIdentifier` and the common values thereof.

**Comment by djc** [comment]
Could/should we share a signature trait with rustls somehow?
