### ISSUE TITLE
0.102 release planning

### ISSUE THREAD

**Issue by djc** [rustls/webpki#159]
Let's gather some context for release blockers

- [x] Update pki-types to 1.0

Done:

- [x] https://github.com/rustls/webpki/pull/147
- [x] https://github.com/rustls/webpki/pull/165
- [x] https://github.com/rustls/webpki/pull/164
- [x] https://github.com/rustls/webpki/pull/163
- [x] https://github.com/rustls/webpki/pull/168
- [x] https://github.com/rustls/webpki/issues/167
- [x] https://github.com/rustls/webpki/pull/50
- [x] https://github.com/rustls/webpki/pull/158
- [x] https://github.com/rustls/webpki/pull/174
- [x] Fix `Budget` in `CertRevocationList` trait.
- [x] ~Push `RevocationOptions` into pki-types to avoid public webpki type in rustls API?~
- [x] https://github.com/rustls/webpki/pull/207

**Comment by cpu** [comment]
Added a few more items to the list (most of which are already merged).

**Comment by djc** [comment]
I think we should defer releasing the final version of this until the final rustls release is also ready, in order to avoid creating more semver-incompatible version branches (that we have to maintain according to our maintenance policy) if it still turns out that we have some churn in the API we want for rustls.

**Comment by cpu** [comment]
That sounds good to me.

**Comment by cpu** [comment]
>  Push RevocationOptions into pki-types to avoid public webpki type in rustls API?

We chatted about this one [in a Discord thread](https://discord.com/channels/976380008299917365/1156981186900541532). Making this change will require moving a lot of types into `pki-types`, most of which are actually specific to webpki and don't look like they would generalize well to other verifiers. There are some additional downsides to this approach as well, like having to un-seal the `CertRevocationList` trait.

The line-item mentions leaking types into the rustls API but presently the webpki revocation types only appear in the webpki verifier bits that are already specific to webpki. The https://github.com/rustls/rustls/pull/1430 issue that may have motivated this change can be accomplished by wrapping the webpki verifier so it doesn't seem like it would justify the work involved.

In sum: I think we're going to table this idea for the 0.22 release and encourage 1430 be solved with other workarounds.

**Comment by ctz** [comment]
> Push ServerName type into pki-types so it can be shared with rustls?

That would include `DnsName` I suppose, so we could remove the duplication there (though it has a modest amount of behaviour for a crate that is so far mostly structural).
 
I guess moving this up could theoretically be a non-breaking change? In the sense that both webpki and rustls could reexport the moved type? That is assuming the type we move is a superset of `webpki::DnsName` and `rustls::DnsName`?

**Comment by ctz** [comment]
Aside from some release engineering (taking pki-types to 1.0, editing versions here) I think this is done?

**Comment by djc** [comment]
Yeah, I think so!
