### ISSUE TITLE
`EndEntityCert` documentation refers to removed methods

### ISSUE THREAD

**Issue by tannaurus** [rustls/webpki#270]
[EndEntityCert's documentation](https://github.com/rustls/webpki/blob/main/src/end_entity.rs#L27) is refers to methods that don't exist when describing what needs to be validated for both client and server tls connections

The following functions [were deprecated since `0.101.2` and subsequently removed](https://github.com/rustls/webpki/commit/b6f3ad3a9871a4cbddcfbc97d0a6f4539d3d1c19):
- `EndEntityCert.verify_is_valid_tls_server_cert`
- `EndEntityCert.verify_is_valid_tls_client_cert`

There's also an additional reference to `verify_is_valid_tls_server_cert` in [tests/generate.py](https://github.com/rustls/webpki/blob/main/tests/generate.py#L212)

**Comment by djc** [comment]
Oops, that's probably my fault -- should have updated the docs in #133.
