### ISSUE TITLE
Supporting x.509 v1 certificates and v3 certificates with no extensions

### ISSUE THREAD

**Issue by lufte** [rustls/webpki#29]
I wonder if it's in the interest of this fork to support these two types of certificates. The original repository already has two open pull requests to add these features:
* https://github.com/briansmith/webpki/pull/234 
* https://github.com/briansmith/webpki/pull/241

**Comment by djc** [comment]
What's your use case for these?

**Comment by fspreiss** [comment]
Support for v3 certificates without extensions is actually quite important for our project, e.g., to be backward-compatible with self-signed certificates (that we generated using [openssl](https://crates.io/crates/openssl)) that are deployed in production and difficult to change.

We were waiting for https://github.com/briansmith/webpki/issues/219 (which has quite a bit of support via 👍) to be resolved (via https://github.com/briansmith/webpki/pull/241) for a long time now (almost 2 years), but unfortunately it hasn't happened yet. For the time being, we are working with a private fork of [briansmith/webpki](https://github.com/briansmith/webpki), but maintaining it is cumbersome and we'd be very happy to see this addressed in [rustls/webpki](https://github.com/rustls/webpki) (e.g., via https://github.com/briansmith/webpki/pull/241).

**Comment by djc** [comment]
#34 has since been merged, so we now accept V3 certificates without extensions. Thanks @fspreiss!

**Comment by cpu** [comment]
I'm quite hesitant to see support for X509 v1 certificates and don't think there's been enough compelling evidence presented to motivate support in to this crate. 

Is that the only remaining aspect keeping this ticket open now that the V3 sans extensions work has landed?

**Comment by djc** [comment]
> I'm quite hesitant to see support for X509 v1 certificates

Why's that?

> Is that the only remaining aspect keeping this ticket open now that the V3 sans extensions work has landed? 

I think so.

**Comment by cpu** [comment]
> Why's that?

I think it's more code surface for limited benefit. X509v3 was standardized in ~1996 and the web PKI has required V3 for over a decade. I believe remaining use-cases of V1 are largely self-signed certificates generated with poor defaults and I don't think the deployment of those certificates in 2023 is wide spread enough to merit adopting workarounds (or at least haven't been convinced of that yet).

**Comment by lufte** [comment]
That sounds like a fair argument. I say we're good with @fspreiss work.

**Comment by djc** [comment]
Thanks for your gracious response, will close this.

**Comment by cpu** [comment]
Do we know that they're in widespread use beyond `test.mosquitto.org`? It seems like an easy fix for the maintainers of that server to fix their certificate. They already have a valid certificate for the same hostname on :443 and a self-issued test PKI should be quite malleable.

**Comment by djc** [comment]
I don't know -- just speculating that there might be some obscure reason some ecosystems are sticking to V1.

**Comment by uglyoldbob** [comment]
I am trying to use the rustls crate write some code for and android auto server. The code I am basing this (aasdk) on uses a version 1 certificate to communicate with the phone. (aasdk can be found at https://github.com/openDsh/aasdk/blob/develop/src/Messenger/Cryptor.cpp#L275)

I don't currently have the ability of obtaining a v3 version of this certificate.

**Comment by uglyoldbob** [comment]
@djc Any thoughts on v1 certs for android auto use case?

**Comment by djc** [comment]
@ctz usually decides these kinds of policy questions.

**Comment by ctz** [comment]
AFAICT this certificate is for client auth; there is no fundamental need for this crate to be parsing that certificate in order to use it with rustls -- see https://github.com/rustls/rustls/issues/1918#issuecomment-2232945160 for the route to achieving that.

**Comment by uglyoldbob** [comment]
@ctz I've used the with_client_cert_resolver method, but webpki still seems to be called in verifying the client certificate and failing with UnsupportedCertVersion. It works if I bring in a modified webpki that supports v1 certificates.

**Comment by uglyoldbob** [comment]
@ctz I used the with_client_cert_resolver from rustls and made it farther on the path that uses unmodified rustls, but the android device seems to not like the handshake data and cuts the connection.

**Comment by djc** [comment]
> [@ctz](https://github.com/ctz) I used the with_client_cert_resolver from rustls and made it farther on the path that uses unmodified rustls, but the android device seems to not like the handshake data and cuts the connection.

That sounds like it might be a different issue/bug? Suggest filing a rustls issue with all the relevant context suggested in the issue template.

**Comment by ctz** [comment]
Yes, please file a separate issue for that and we'll help if we can.
