### ISSUE TITLE
webpki does not validate certificates with name constraints

### ISSUE THREAD

**Issue by olix0r** [rustls/webpki#3]
We (Linkerd) have recently noticed a bug (https://github.com/linkerd/linkerd2/issues/9299) that prevents webpki from validating certificates that include name constraints. We can probably produce a smaller reproduction outside of Linkerd, but our testing indicates that this applies to any certificate issued by a CA that uses name constraints. https://github.com/briansmith/webpki/issues/20 suggests that this issue has existed for quite a while.

Last year, the folks at Deno ran into this issue (https://github.com/denoland/deno/issues/10312) and @bnoordhuis kindly put together a PR (https://github.com/briansmith/webpki/pull/226). We have not yet confirmed that this PR fixes the bugs that we encountered, but it would be great to find a path forward for name constraint support.

**Comment by hawkw** [comment]
It looks like simply opening @bnoordhuis' change against this fork is blocked on an upstream change to `ring` (https://github.com/briansmith/webpki/pull/226#issuecomment-1254148923) which looks like it may not be going to happen (https://github.com/briansmith/ring/pull/1265).

It's possible there's an alternative solution that doesn't require `ring` changes?

**Comment by bnoordhuis** [comment]
I've opened #7. It copies a few bits from ring. Not great but the least worst solution I could come up with.

**Comment by hawkw** [comment]
Thanks!
