### ISSUE TITLE
0.100.0 release planning

### ISSUE THREAD

**Issue by djc** [rustls/webpki#35]
I think this is pretty much ready to go?

- #10 -- might be nice to get in, but it doesn't have any API changes
- #6 -- no API changes either, I think

Now that we added `CertificateError::Revoked` in rustls, should add an `Error::Revoked` here?

**Comment by kinnison** [comment]
I literally just ran into not being able to use this because of dependencies of dependencies etc.  So the sooner you are ready for 0.21 of rustls (via this release I guess) the better from my perspective - is there anything I, as an inexperienced third party, can do to help?

**Comment by djc** [comment]
@kinnison is this for rustup? You should probably just follow the rustls tracking issue directly. I expect we'll be able to push out rustls 0.21 in the coming week.

**Comment by kinnison** [comment]
No, this is a personal project. So it's far less urgent in that sense 😂

**Comment by ctz** [comment]
> Now that we added `CertificateError::Revoked` in rustls, should add an `Error::Revoked` here?

I don't think so, now webpki::Error is `non_exhaustive` we can add it when webpki has some sort of revocation checking.

**Comment by ctz** [comment]
https://crates.io/crates/rustls-webpki/0.100.0
