### ISSUE TITLE
Upgrade "soft" deprecations

### ISSUE THREAD

**Issue by cpu** [rustls/webpki#47]
In two places (`Time::try_from` and `From::from` for `DnsName`) there are "soft" deprecation comments:

https://github.com/rustls/webpki/blob/6dd4a44d6d1fee5e790c6c19825435213e5cec6d/src/time.rs#L26-L31

https://github.com/rustls/webpki/blob/6dd4a44d6d1fee5e790c6c19825435213e5cec6d/src/subject_name/dns_name.rs#L57-L64

We should consider replacing these with "hard" [deprecated attributes](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) so that the the deprecations are warned about. Probably best done as part of the next breaking changeset.

**Comment by djc** [comment]
I think we can just get the `#[deprecated]` attributes in now. This doesn't break the API, just adds warnings (which is not considered to be semver-incompatible) -- and don't forget that rustls is by far the largest direct user of webpki anyway.
