### ISSUE TITLE
relationship of this repository to the original

### ISSUE THREAD

**Issue by webern** [rustls/webpki#8]
This repository is reported as a fork of https://github.com/briansmith/webpki. Will this repository be publishing to https://crates.io/crates/webpki (which currently reports https://github.com/briansmith/webpk as its git repository)? Seems like it since it is under the rustls org.

It might be worth mentioning in the readme since it reports as a fork.

**Comment by djc** [comment]
It will be published as rustls-webpki, which you can see from the Cargo manifest.

**Comment by webern** [comment]
Sorry if the question wasn't clear, sorry I didn't read the manifest.

So as I understand it now, `webpki-roots` will switch this line to read `rustls-webpki` https://github.com/rustls/webpki-roots/blob/43b451f2d63084f9e272ef9b3fac74c5353c57a5/Cargo.toml#L13 and this will effectively deprecate the original `webpki` crate in the ecosystem (or start that process).

**Comment by djc** [comment]
Yes, I think the idea is that future releases of webpki-roots and rustls might switch to rustls-webpki.

**Comment by michalfita** [comment]
>Yes, I think the idea is that future releases of webpki-roots and rustls might switch to rustls-webpki.

Apologize being impatient, but **how soon**?

**Comment by djc** [comment]
We don't have a defined timeline. I expect it will happen in the next 2-3 months.

**Comment by ctz** [comment]
I think https://github.com/rustls/webpki#about-this-fork covers this now.
